title = "Affordable"
body = '''
Space poses a unique set of challenges not commonly faced on Earth. Increased demand for performance and reliability lead to higher development costs.

Space Cubics is a join effort between<br>private sector engineers with extensive astrocomputing experience <br>and JAXA experts with a keen interest in robust testing.<br><br>As a JAXA-backed venture, we strive to provide reliable space computers at an accessible price.
'''
