name: Link Check

on:
  pull_request:
    paths-ignore:
      - AGENTS.md
      - doc/**
      - README.md

jobs:
  lychee:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ZOLA_BIN: ${{ github.workspace }}/zola
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Install http-server
        run: |
          npm install -g http-server

      - name: Install Zola
        run: |
          ZOLA_VERSION=$(cat ZOLA_VERSION)
          curl -sL "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
          $ZOLA_BIN --version

      - name: Build base site
        run: |
          "$ZOLA_BIN" build --base-url "http://127.0.0.1:1111"

      - name: Run HTTP Server
        run: |
          http-server public -p 1111 &

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config .lychee.toml
            --verbose
            --root-dir "$PWD/public"
            "public/**/*.html"
